# Generated by Django 6.0.3 on 2026-03-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_description_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
