# Generated by Django 6.0.3 on 2026-04-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_category_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='modified_by',
        ),
    ]
