# Generated by Django 6.0.3 on 2026-04-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_remove_expense_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
